CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
      SELECT DISTINCT salary FROM (SELECT id,salary,DENSE_RANK() OVER(ORDER BY salary DESC)AS r FROM Employee) AS t WHERE r=N

  );
END
